spring:
  datasource:
    username: ${USERNAME}
    url: ${URL}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/alzheimerdinger}

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:transcript-consumer-group}
    analysis-group:
      group-id: ${KAFKA_CONSUMER_ANALYSIS_GROUP:analysis-consumer-group}
    cognitive-group:
      group-id: ${KAFKA_CONSUMER_COGNITIVE_GROUP:cognitive-consumer-group}

    topics:
      transcript: ${KAFKA_TOPIC_TRANSCRIPT:transcript}
      emotion-analysis: ${KAFKA_TOPIC_EMOTION_ANALYSIS:emotion-analysis}
      cognitive-report: ${KAFKA_TOPIC_COGNITIVE_REPORT:cognitive-report}


jwt:
  key: fdsafdsafdsafdsafdsafdsafdsafdsafdsafdsafda
  access:
    expiration: 360000

exclude-auth-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - path-pattern: /api/users/login
      method: POST

exclude-blacklist-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - path-pattern: /api/users/login
      method: POST