name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
title: '이슈 제목을 작성해주세요'
labels:
  - feat
assignees: []   # 필요없으면 빈 배열로 두세요.

body:
  - type: textarea
    id: description
    attributes:
      label: '📝 상세 내용 (Description)'
      description: '이슈에 대한 설명을 작성해주세요'
      placeholder: |
        - 구현할 기능
        - 고려 사항
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 체크리스트 (Tasks)'
      description: '필요한 작업 목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
