name: CD Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot JAR
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/your-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-app:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/your-app:${{ github.sha }} \
                     ${{ secrets.DOCKERHUB_USERNAME }}/your-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GCE via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            # 1) 작업 디렉터리(프로젝트 폴더)로 이동
            cd /opt/your-app

            # 2) runtime 설정 파일(.env) 생성
            cat <<EOF > .env
            MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
            MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}

            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}

            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}

            GRAFANA_ADMIN_USER=${{ secrets.GRAFANA_ADMIN_USER }}
            GRAFANA_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASSWORD }}

            KAFKA_BOOTSTRAP_SERVERS=kafka:9092
            EOF

            # 3) GCP 키 파일 복원
            mkdir -p secret
            cat <<EOF > secret/alzheimerdinger.json
            ${{ secrets.GCP_SA_KEY_JSON }}
            EOF

            # 4) Docker Compose로 최신 이미지 내려받아 재시작
            docker-compose pull springboot
            docker-compose up -d --remove-orphans
